Milestone - Corrections
ProgramKingAbel/portfolio pull request #1
Opened 2023-04-27 14:11 UTC by ProgramKingAbel

- Porfolio Mobile Version 
- Functioning Contact Form linked to FormSpree
- Portfolio Desktop Version
- Pop Up Modal For the Projects
- Implemented Local Storage for form data.

2023-04-27 23:30 UTC, medaminedev66 requested changes
@ProgramKingAbel 
### This is a manual review
# Request Changes ♻️ 
_Please check out the comments under the review._

Cheers and Happy coding!:clap::clap::clap:

2023-04-27 23:30 UTC, medaminedev66 commented on index.html
> +        </div> -->
- [ ] It's preferable not to commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

2023-04-27 23:30 UTC, medaminedev66 commented on index.html
> +            <!-- </div> -->
- [ ] According to HTML and CSS best practices, it's better not to commit old pieces of code.

2023-04-27 23:30 UTC, medaminedev66 commented on styles.css
> +  display: flex;
I can see that there are a lot of repeated CSS rules in your code. If you want to create a CSS rule for multiple elements, use a class attribute instead. For example, instead of using display: flex; 3 times
```css
    #intro1 {display: flex; font-size: 10px; font-weight: bold;}
    header {display: flex; font-size: 20px; background-color: green;}
    #banner {display: flex; font-size: 30px; background-image: url(images/static.jpg);}
```
you can create a class and add it to all element that need to be blue.
```css
   .flex{display: flex;;}
```
According to project guidelines, you should follow [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2023-04-27 23:30 UTC, medaminedev66 commented on script.js
> +        <i data-modal-close class="uil uil-multiply" id="close-btn-modal"></i>
- [ ] The close button in the popup does not function as expected. According to project requirements, when the user clicks (or taps) the close (X) button, the popup should disappear.

2023-04-27 23:30 UTC, medaminedev66 commented on script.js
> +        </div>
- [ ] The modal design still needs improvement. The modal design should be responsive with all desktop screen sizes. Currently your modal does not fit the screen size with this resolution (1024px * 560px).  As you can see on the screenshot below, the header and the bottom do not show up. You may work on the height of the modal so that the modal can fit the screen size. You can also add a vertical scrolling bar if necessary. I also recommend using dev tool to test the modal design on different screen sizes.
- Your design:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/77190203/235009552-fdf3ee08-91c0-4e3b-bad4-2aef94ebd986.png">

2023-04-27 23:30 UTC, medaminedev66 commented on index.html
> +    </section>
- [ ] According to project requirements, you should add social icons to the contact section since they're exist in the Figma design. Kindly take a look at the requirement below:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/77190203/235007789-a55a8b9a-4045-46e4-86ad-970fed070a90.png">

2023-04-27 23:30 UTC, medaminedev66 commented on script.js
> +  // console.log(projectsContainer);
- [ ] Kindly remove this commented code for a clean code. Please ensure to remove all commented console.log from your codes so that your code is clean.

2023-04-27 23:30 UTC, medaminedev66 commented on styles.css
> +}
- [ ] A blurred background should be present outside of the popup, as per the Figma design.
- Figma design:
![image](https://user-images.githubusercontent.com/77190203/235011645-22bd5a35-08df-4800-b962-1baf01305a74.png)

2023-04-27 23:30 UTC, medaminedev66 commented on styles.css
> +  }
- [ ] To improve your UI:
  - please make sure to use the same font size for the menu list that is specified in the Figma design. 
  - The menu elements should all be aligned to the left so that your design matches the Figma design. 

Kindly take a look at the screenshots below: 
Your design:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/77190203/235010171-75830130-c90d-4c5a-a9c5-429ac061221c.png">
Figma design:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/77190203/235010371-c196dea6-37ee-4291-8fac-c06911fedf3a.png">

2023-04-27 23:30 UTC, medaminedev66 commented on styles.css
> +}
- [ ] In Mobile design, the margins used for the popup are not the same as the ones provided in Figma design. Kindly take a look at the screenshots below:
Your design:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/77190203/235010646-6e8d552d-df9a-44dc-ad96-7d2b8870ec7b.png">
Figma design:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/77190203/235010793-8a65fb97-f778-46fa-9129-1927fafb7170.png">

2023-04-27 23:30 UTC, medaminedev66 commented on index.html
> +                <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
- [ ] According to project requirements, when the user clicks (or taps) any of the mobile menu options, the correct part of the page should be displayed. Currently, clicking on a menu option only closes the menu.

2023-05-01 14:48 UTC, bellom approved these changes
@ProgramKingAbel,

### This is a manual review

Because the file path is the only issue, I will go ahead and approve this PR, it would be nice to make the necessary changes before merging.

# Approved :+1:

Cheers and Happy coding!:clap::clap::clap:

2023-05-01 14:48 UTC, bellom commented on script.js
> +    img: '/images/Tonic.svg',
With this file path, your image is not showing:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/31897434/235469648-ded82978-2999-42ee-8849-3573fa4134ba.png">

Try this instead 👉 `    img: 'images/Tonic.svg',` 

I trust you would correct this before merging 👍

2023-05-01 15:22 UTC, ProgramKingAbel commented on script.js
> +    img: '/images/Tonic.svg',
I have made the changes. Thank you for the guidance.

2023-05-01 15:24 UTC, merged